### ISSUE TITLE
Support automated site build

### ISSUE THREAD

**Issue by emdupre** [poldrack/poldracklab-staging.github.io#11]
@emdupre
> Would you be able to upload the original, supporting files -- possibly on another branch ? We could then add a github action to build those and deploy to a gh-pages branch for rendering.

@poldrack 
> would be great to add a github action, but building the files is nontrivial since it pulls info from my academicdb database which requires credentials. we should discuss whether there is a better way to do it.
> BTW - I'm working on the automated build right now.

mentioned in #1

**Comment by effigies** [comment]
Now working. I think you can remove `docs/` (and add to `.gitignore`) from the main branch.

**Comment by poldrack** [comment]
this is done, and the site has been transitioned to poldracklab.github.io - thanks again for your help!
