### ISSUE TITLE
The projects section seems sparse in the "cognitive neuroscience projects" section

### ISSUE THREAD

**Issue by bissettp** [poldrack/poldracklab-staging.github.io#5]
As currently formulated, one might think that the only empirical projects we have are dense scanning. Though this is a big thrust of what we do, it might be worth mentioning some of the other projects we've done or are doing, including the UH2/SOBC project and response inhibition analyses/modeling.

**Comment by poldrack** [comment]
ok, added a bunch more, lmk if this is sufficient, or propose edits
